CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER default null, P_PROCENT NUMBER default 5, P_PRET_NOU OUT NUMBER) IS
    V_PRET NUMBER;
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS = NVL(P_ID_PRODUS, ID_PRODUS)
    RETURNING PRET_LISTA INTO P_PRET_NOU;
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN 
            UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS = NVL(P_ID_PRODUS, ID_PRODUS);
            P_PRET_NOU:=SQL%ROWCOUNT; --VOI RETURNA NR DE RANDURI MODIFICATE, NU PRETUL NOU
END;
/

DECLARE 
    P NUMBER;
BEGIN
    MARESTE_PRET_PROD3(P_ID_PRODUS=>2378, P_PROCENT=>10, P_PRET_NOU=>P);
    IF P IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE: ' || P);
    END IF;
END;
/


DECLARE 
    P NUMBER;
BEGIN 
    MARESTE_PRET_PROD3(P_PRET_NOU=>P);
        IF P IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('PRETUL NOU/NR DE RANDURI ACTUALIZATE ESTE: ' || P);
        ELSE
         DBMS_OUTPUT.PUT_LINE('NU S-A MODIFICAT NICIUN PRET');
    END IF;
END;
/


--SA SE CONSTRUIASCA O PROCEDURA CARER PRIMESTE O CATEGORIE DE PRODUSE SI AFISEAZA DENUMIREA FIECARUI PRODUS DIN ACEA CATEGORIE PRECUM SI VALOARE TOTALA 
--A COMENZILOR PENTRU FIECARE PRODUS. DACA CATEG NU EXISTA, SA SE RIDICE O EXCEPTIE
--SA SE APELEZE PROEDURA SI SA SE TRATEZE RESPECTIVA EXCEPTIE IN BLOCUL APELATOR
SELECT * FROM PRODUSE;
    SELECT P.DENUMIRE_PRODUS, SUM(R.CANTITATE * R.PRET) FROM PRODUSE P, RAND_COMENZI R WHERE P.CATEGORIE='' AND P.ID_PRODUS=R.ID_PRODUS group by P.DENUMIRE_PRODUS;
    
    
CREATE OR REPLACE PROCEDURE AFISARE(P_CATEGORIE VARCHAR2) IS 
    CURSOR C IS SELECT P.DENUMIRE_PRODUS, SUM(R.CANTITATE * R.PRET) AS VALOARE FROM PRODUSE P, RAND_COMENZI R WHERE P.CATEGORIE=P_CATEGORIE AND P.ID_PRODUS=R.ID_PRODUS GROUP BY P.DENUMIRE_PRODUS;
    R C%ROWTYPE;
BEGIN
    OPEN C;
    LOOP
    FETCH C INTO R;
    EXIT WHEN C%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('DENUMIRE:' ||  R.DENUMIRE_PRODUS || 'VALOARE: '||  R.VALOARE);
    END LOOP;
    DBMS_OUTPUT.put_line('Numar produse in categorie pentru care exista comenzi:' || C%ROWCOUNT);
    IF C%ROWCOUNT=0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'NU SUNT PRODUSE IN ACEA CATEGORIE'); 
    END IF;

END;
/

DECLARE 
    NU_EXISTA_PROD EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA_PROD, -20000);
    CATEG VARCHAR2(20) := 'hardwae1';
    
BEGIN
    AFISARE(P_CATEGORIE=>CATEG);
    EXCEPTION WHEN NU_EXISTA_PROD THEN 
        DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE: ' || SQLERRM); 
END;
/  

-- SA SE CONSTRUIASCA O FUNCTIE CARE PRIMESTE ID-UL UNUI PRODUS SI RETURNEAZA VALOAREA TOTALA A COMENZILOR PENTRU RESPECTIVUL PRODUS
-- SA SE APELEZE FUNCTIA DINTR-UN CURSOR

CREATE OR REPLACE FUNCTION GET_VAL_COM_PRODUS(P_ID_PRODUS NUMBER) RETURN NUMBER IS 
V_VAL NUMBER;
BEGIN
    SELECT SUM(PRET*CANTITATE) INTO V_VAL FROM RAND_COMENZI WHERE ID_PRODUS=P_ID_PRODUS;
    RETURN NVL(V_VAL, 0);
END;
/


SELECT * FROM RAND_COMENZI ORDER BY ID_PRODUS;
    
BEGIN 
    DBMS_OUTPUT.PUT_LINE('VALOARE COMENZI:' || GET_VAL_COM_PRODUS(1797));
END;
/

--FUNCTIILE DEFINITE POT FUNCTIONA CA SI FUNCTII SQL IN COMENZI SQL
SELECT ID_PRODUS, DENUMIRE_PRODUS, GET_VAL_COM_PRODUS(ID_PRODUS) VAL FROM PRODUSE
WHERE GET_VAL_COM_PRODUS(ID_PRODUS)>5000
ORDER BY GET_VAL_COM_PRODUS(ID_PRODUS) DESC;
    
DECLARE 
    CURSOR C IS SELECT ID_PRODUS, DENUMIRE_PRODUS, GET_VAL_COM_PRODUS(ID_PRODUS) VAL FROM PRODUSE
WHERE GET_VAL_COM_PRODUS(ID_PRODUS)>5000
ORDER BY GET_VAL_COM_PRODUS(ID_PRODUS) DESC;

BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS || '->' || R.DENUMIRE_PRODUS || '->' || R.VAL);
    END LOOP;
END;
/
    
    
--PACHETELE GRUPEAZA FUNCTII SI PROCEDURI + VARIABILE, CURSORI, EXCEPTII, TYPE-URI ETC
    --SPECIFICATII (PUBLICA)
    --BODY (PRIVATA), AICI SUNT IMPLEMENTARILE
--PUTEM SUPRAINCARCA FUNCTII SI PROCEDURI IN CADRUL UNUI PACHET
-- IN BODY TRB IMPLEMENTATE CEL PUTIN FUNC SI PROC DIN SPEC
--PUTEM AVEA SI FUNCTII SI PROCEDURIPRIVATE
-- O FUCNTIE SAU PROC PRIVATA POATE FI APELATA IN ACELASI PACHET POATE FI APELATA DOAR DE O FCT SAU PROC CARE O URMEAZA(FORWARD DECLARATION)

CREATE OR REPLACE PACKAGE BODY MYPACK_1061 IS
    V_COTA NUMBER(2):=21;
    PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER) IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('SUMA ESTE: ' || (N1+N2));
    END;
    FUNCTION MULTIPLY_NUMBERS(N1 NUMBER, N2 NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN N1*N2;
    END;
END;
/

BEGIN 
    MYPACK_1061.V_COTA:=25;
    DBMS_OUTPUT.PUT_LINE('COTA=' || MYPACK_1061.V_COTA);
    MYPACK_1061.ADD_NUMBERS(10, 20);
    DBMS_OUTPUT.PUT_LINE('INMULTIREA ESTE: ' || MYPACK_1061.MULTIPLY_NUMBERS(10, 20));
END;
/
