FOLOSIND O COLECTIE SA SE AFISZE DENUMIREA PRODUSELOR, VALOAREA TOTALA A COMENZILOR 
PRECUM SI DATA ULTIMEI COMENZI PENTRU PRODUSUL RESPECTIV
SE VOR AFISA PRODUSELE ORDONATE DESCRESCATOR DUPA DATA ULTIMEI COMENZI 


DECLARE
  TYPE T_REC IS RECORD(
    DENUMIRE VARCHAR2(30),
    VAL_TOTALA NUMBER(20),
    DATA_ULTIMEI_COMENZI TIMESTAMP);
  TYPE T_PROD IS TABLE OF T_REC INDEX BY PLS_INTEGER; --INDEX BY TABLE/ASSOCIATIVE ARRAY
  V T_PROD;
  I PLS_INTEGER;
BEGIN
  SELECT P.DENUMIRE_PRODUS, SUM(R.PRET*R.CANTITATE), MAX(C.DATA) BULK COLLECT INTO V FROM RAND_COMENZI R, PRODUSE P, COMENZI C WHERE R.ID_PRODUS=P.ID_PRODUS AND R.ID_COMANDA=C.ID_COMANDA
   GROUP BY P.DENUMIRE_PRODUS
   ORDER BY MAX(C.DATA) DESC;
 
 I:=V.FIRST;
 WHILE I IS NOT NULL LOOP
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I).DENUMIRE||' '||V(I).VAL_TOTALA||' '||V(I).DATA_ULTIMEI_COMENZI);
   I:=V.NEXT(I);   
 END LOOP;
V.DELETE;
END;
/


DECLARE
  TYPE T_REC IS RECORD(
    DENUMIRE VARCHAR2(30),
    VAL_TOTALA NUMBER(20),
    DATA_ULTIMEI_COMENZI TIMESTAMP);
  TYPE T_PROD IS TABLE OF T_REC; --NESTED TABLE
  V T_PROD;
  I PLS_INTEGER;
BEGIN
  SELECT P.DENUMIRE_PRODUS, SUM(R.PRET*R.CANTITATE), MAX(C.DATA) BULK COLLECT INTO V FROM RAND_COMENZI R, PRODUSE P, COMENZI C WHERE R.ID_PRODUS=P.ID_PRODUS AND R.ID_COMANDA=C.ID_COMANDA
   GROUP BY P.DENUMIRE_PRODUS
   ORDER BY MAX(C.DATA) DESC;
 V.TRIM(1);
 I:=V.FIRST;
 WHILE I IS NOT NULL LOOP
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I).DENUMIRE||' '||V(I).VAL_TOTALA||' '||V(I).DATA_ULTIMEI_COMENZI);
   I:=V.NEXT(I);   
 END LOOP;
V.DELETE;
END;
/

DECLARE
  TYPE T_REC IS RECORD(
    DENUMIRE VARCHAR2(30),
    VAL_TOTALA NUMBER(20),
    DATA_ULTIMEI_COMENZI TIMESTAMP);
  TYPE T_PROD IS VARRAY(200) OF T_REC; --VARRAY
  V T_PROD;
  I PLS_INTEGER;
BEGIN
  SELECT P.DENUMIRE_PRODUS, SUM(R.PRET*R.CANTITATE), MAX(C.DATA) BULK COLLECT INTO V FROM RAND_COMENZI R, PRODUSE P, COMENZI C WHERE R.ID_PRODUS=P.ID_PRODUS AND R.ID_COMANDA=C.ID_COMANDA
   GROUP BY P.DENUMIRE_PRODUS
   ORDER BY MAX(C.DATA) DESC;
 V.TRIM(5); --TRIM ESTE SPECIFIC VARRAY/NESTED TABLE SI STERGE ELEMENTE DE LA FINALUL COLECTIEI
 I:=V.FIRST;
 WHILE I IS NOT NULL LOOP
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I).DENUMIRE||' '||V(I).VAL_TOTALA||' '||V(I).DATA_ULTIMEI_COMENZI);
   I:=V.NEXT(I);   
 END LOOP;
V.DELETE;
END;
/


--CURSORUL
--    - IMPLICIT(CURSORUL SQL)
--      - SQL%FOUND, SQL%NOTFOUND, SQL%ROWCOUNT, SQL%ISOPEN (NU PREA ARE UTILITATE)
--    - EXPLICIT

DECLARE
  TYPE T_REC IS RECORD(
    DENUMIRE VARCHAR2(30),
    VAL_TOTALA NUMBER(20),
    DATA_ULTIMEI_COMENZI TIMESTAMP);
  TYPE T_PROD IS VARRAY(200) OF T_REC; --VARRAY
  V T_PROD;
  I PLS_INTEGER;
BEGIN
  SELECT P.DENUMIRE_PRODUS, SUM(R.PRET*R.CANTITATE), MAX(C.DATA) BULK COLLECT INTO V FROM RAND_COMENZI R, PRODUSE P, COMENZI C WHERE R.ID_PRODUS=P.ID_PRODUS AND R.ID_COMANDA=C.ID_COMANDA
   GROUP BY P.DENUMIRE_PRODUS
   ORDER BY MAX(C.DATA) DESC;
   
   DBMS_OUTPUT.PUT_LINE(V.COUNT);
   DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
END;
/

-- SA SE MAREASCA CU 5% SALARIUL ANG CARE AU INTERMEDIAT CEL PUTIN 2 COMENZI.
-- SA SE AFISEZE NUMARUL SALARIILOR MARITE

BEGIN 
    UPDATE ANGAJATI SET SALARIUL=SALARIUL*1.05 WHERE ID_ANGAJAT IN 
    ( SELECT ID_ANGAJAT FROM COMENZI GROUP BY ID_ANGAJAT HAVING COUNT(*)>=2);
    IF SQL%FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('S-AU MODIFICAT SALARII');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NU S-AU MODIFICAT SALARII');
    END IF;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);

END;
/

-- SA SE MAREASCA CU 5% SALARIUL ANG CARE AU INTERMEDIAT CEL PUTIN 2 COMENZI.
-- SA SE AFISEZE NUMARUL SALARIILOR MARITE SI ID-URILE ANGAJATILOR CARE AU PRIMIT MARIRE

DECLARE
TYPE T_ANG IS TABLE OF NUMBER;
V T_ANG;

BEGIN 
    UPDATE ANGAJATI SET SALARIUL=SALARIUL*1.05 WHERE ID_ANGAJAT IN 
    ( SELECT ID_ANGAJAT FROM COMENZI GROUP BY ID_ANGAJAT HAVING COUNT(*)>=2) RETURNING ID_ANGAJAT BULK COLLECT INTO V;
    IF SQL%FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('S-AU MODIFICAT SALARII');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NU S-AU MODIFICAT SALARII');
    END IF;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    
    FOR I IN 1..V.COUNT LOOP 
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;
    ROLLBACK;
END;
/

--SA SE STEARGA TOATE PRODUSELE CARE NU AU FOST COMANDATE NICIODATE
--SA SE AFISEZE NUMARUL DE PRODUSE STERSE PRECUM SI DENUMIREA LOR

DECLARE
TYPE T_PROD IS TABLE OF VARCHAR2(100);
V T_PROD;

BEGIN 
    DELETE FROM PRODUSE WHERE ID_PRODUS NOT IN 
    (SELECT ID_PRODUS FROM RAND_COMENZI) RETURNING DENUMIRE_PRODUS BULK COLLECT INTO V;
    IF SQL%FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('S-AU STERS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NU S-AU STERS PRODUSE');
    END IF;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    
    FOR I IN 1..V.COUNT LOOP 
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;

END;
/

DECLARE
TYPE T_REC IS TABLE OF PRODUSE%ROWTYPE;
V T_PROD;

BEGIN 
    DELETE FROM PRODUSE WHERE ID_PRODUS NOT IN 
    (SELECT ID_PRODUS FROM RAND_COMENZI) RETURNING ID_PRODUS, DENUMIRE_PRODUS, DESCRIERE, CATEGORIE, PRET_LISTA, PRET_MIN BULK COLLECT INTO V;
    IF SQL%FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('S-AU STERS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NU S-AU STERS PRODUSE');
    END IF;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    
    FOR I IN 1..V.COUNT LOOP 
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;

END;
/














