--FOLOSIND UN CURSOR SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR DIN RESPECTIVELE CATEGORII
--SE VOR AFISA DOAR CATEGORIILE CU VALOAR TOTALA A COMENZILOR > 50000
--PENTRU FIECARE CATEGORIE, SE VOR AFISA PRODUSELE DIN ACEA CATEGORIE SI VALOAREA TOTALA A COMENZILOR

SELECT CATEGORIE, produse FROM PRODUSE WHERE ID_PRODUS IN (SELECT ID_PRODUS FROM RAND_COMENZI HAVING(SUM(PRET*CANTITATE)>50000) GROUP BY ID_PRODUS);



DECLARE
 CURSOR C IS SELECT P.CATEGORIE, SUM(R.PRET*R.CANTITATE) VALOARE_TOTALA
 FROM PRODUSE P, RAND_COMENZI R WHERE P.ID_PRODUS=R.ID_PRODUS
 GROUP BY P.CATEGORIE, P.DENUMIRE_PRODUS, R.PRET*R.CANTITATE
 HAVING SUM(R.PRET*R.CANTITATE)>50000;
 CURSOR D IS SELECT P.DENUMIRE_PRODUS, CATEGORIE,  SUM(R.PRET*R.CANTITATE) AS VALOARE_TOTALA FROM PRODUSE P, RAND_COMENZI R WHERE P.ID_PRODUS=R.ID_PRODUS AND P.CATEGORIE=CATEGORIE
 GROUP BY CATEGORIE, P.DENUMIRE_PRODUS
 HAVING SUM(R.PRET*R.CANTITATE)>50000;
 
BEGIN
FOR R IN C LOOP
    DBMS_OUTPUT.PUT_LINE(R.CATEGORIE||': '||R.VALOARE_TOTALA);
    FOR S IN D LOOP 
    IF S.CATEGORIE=R.CATEGORIE THEN
    DBMS_OUTPUT.PUT_LINE('   ' || S.denumire_produs||': ' || S.VALOARE_TOTALA);
    END IF;
    END LOOP;
END LOOP;
END;
/

DECLARE
 CURSOR C IS SELECT P.CATEGORIE, SUM(R.PRET*R.CANTITATE) VALOARE_TOTALA
 FROM PRODUSE P, RAND_COMENZI R WHERE P.ID_PRODUS=R.ID_PRODUS
 GROUP BY P.CATEGORIE, P.DENUMIRE_PRODUS, R.PRET*R.CANTITATE
 HAVING SUM(R.PRET*R.CANTITATE)>50000;
 CURSOR D (P_CATEG VARCHAR2) IS SELECT P.DENUMIRE_PRODUS, CATEGORIE,  SUM(R.PRET*R.CANTITATE) AS VALOARE_TOTALA FROM PRODUSE P, RAND_COMENZI R WHERE P.ID_PRODUS=R.ID_PRODUS AND P.CATEGORIE='HARDWARE4'
 GROUP BY CATEGORIE, P.DENUMIRE_PRODUS;
 
BEGIN
FOR R IN C LOOP
    DBMS_OUTPUT.PUT_LINE(R.CATEGORIE||': '||R.VALOARE_TOTALA);
    FOR S IN D(R.CATEGORIE) LOOP 
    DBMS_OUTPUT.PUT_LINE('   ' || S.denumire_produs||': ' || S.VALOARE_TOTALA);
    END LOOP;
END LOOP;
END;
/

--SA SE AFISEZE NUMELE SI PRENUMELE CLIENTULUI CARE ARE VALOAREA CEA MAI MARE A COMENZILOR
--SE VOR AFISA COMENZILE PENTRU RESPECTIVUL CLIENT  
    ID_COMANDA, DATA, VALOARE TOTALA A COMENZII
SELECT * FROM COMENZI;

SELECT CL.NUME_CLIENT || CL.PRENUME_CLIENT  FROM CLIENTI CL, COMENZI C, RAND_COMENZI R WHERE CL.ID_CLIENT=C.ID_CLIENT AND C.ID_COMANDA=R.ID_COMANDA
GROUP BY CL.NUME_CLIENT, CL.PRENUME_CLIENT
ORDER BY SUM(R.PRET*CANTITATE) DESC FETCH FIRST 1 ROW ONLY;


SELECT C.ID_COMANDA, C.DATA, SUM(R.PRET*CANTITATE) AS VALOARE_TOTALA FROM COMENZI C, RAND_COMENZI R WHERE C.ID_COMANDA=R.ID_COMANDA AND C.ID_CLIENT=(
SELECT ID_CLIENT  FROM CLIENTI WHERE NUME_CLIENT || PRENUME_CLIENT = (
SELECT CL.NUME_CLIENT || CL.PRENUME_CLIENT  FROM CLIENTI CL, COMENZI C, RAND_COMENZI R WHERE CL.ID_CLIENT=C.ID_CLIENT AND C.ID_COMANDA=R.ID_COMANDA
GROUP BY CL.NUME_CLIENT, CL.PRENUME_CLIENT
ORDER BY SUM(R.PRET*CANTITATE) DESC FETCH FIRST 1 ROW ONLY))
GROUP BY C.ID_COMANDA, C.DATA;

DECLARE 
CURSOR C IS SELECT CL.NUME_CLIENT, CL.PRENUME_CLIENT, SUM(R.PRET*CANTITATE) AS VALOARE_TOTALA FROM CLIENTI CL, COMENZI C, RAND_COMENZI R WHERE CL.ID_CLIENT=C.ID_CLIENT AND C.ID_COMANDA=R.ID_COMANDA
GROUP BY CL.NUME_CLIENT, CL.PRENUME_CLIENT
ORDER BY SUM(R.PRET*CANTITATE) DESC FETCH FIRST 1 ROW ONLY;

CURSOR D IS SELECT C.ID_COMANDA, C.DATA , SUM(R.PRET*CANTITATE) AS VALOARE_TOTALA FROM COMENZI C, RAND_COMENZI R WHERE C.ID_COMANDA=R.ID_COMANDA AND C.ID_CLIENT=(
SELECT ID_CLIENT  FROM CLIENTI WHERE NUME_CLIENT || PRENUME_CLIENT = (
SELECT CL.NUME_CLIENT || CL.PRENUME_CLIENT  FROM CLIENTI CL, COMENZI C, RAND_COMENZI R WHERE CL.ID_CLIENT=C.ID_CLIENT AND C.ID_COMANDA=R.ID_COMANDA
GROUP BY CL.NUME_CLIENT, CL.PRENUME_CLIENT
ORDER BY SUM(R.PRET*CANTITATE) DESC FETCH FIRST 1 ROW ONLY))
GROUP BY C.ID_COMANDA, C.DATA;

BEGIN
FOR R IN C LOOP
DBMS_OUTPUT.PUT_LINE(R.NUME_CLIENT || ' ' || R.PRENUME_CLIENT);
    FOR S IN D LOOP
    DBMS_OUTPUT.PUT_LINE('    ' || S.ID_COMANDA || ' ' || S.DATA || ' ' || S.VALOARE_TOTALA);
    END LOOP;
END LOOP;

END;
/


--CURSORUL CU PARAMETRU
--SA SE AFISEZE NUMELE SI PRENUMELE CLIENTULUI CARE A DAT CELE MAI MULTE COMENZI
--SE VOR AFISA COMENZILE PENTRU RESPECTIVUL CLIENT  
    ID_COMANDA, DATA, VALOARE TOTALA A COMENZII

SELECT C.ID_CLIENT, PRENUME_CLIENT, NUME_CLIENT, COUNT(*) FROM CLIENTI C JOIN COMENZI O ON C.ID_CLIENT=O.ID_CLIENT
GROUP BY C.ID_CLIENT, PRENUME_CLIENT, NUME_CLIENT
ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW WITH TIES;

SELECT C.ID_COMANDA, DATA, SUM(PRET*CANTITATE) VAL
FROM COMENZI C JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
GROUP BY C.ID_COMANDA, DATA;

DECLARE
CURSOR C1 IS SELECT C.ID_CLIENT, PRENUME_CLIENT, NUME_CLIENT, COUNT(*) FROM CLIENTI C JOIN COMENZI O ON C.ID_CLIENT=O.ID_CLIENT
GROUP BY C.ID_CLIENT, PRENUME_CLIENT, NUME_CLIENT
ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW WITH TIES;

CURSOR C2 (P_ID_CLIENT NUMBER) IS SELECT C.ID_COMANDA, DATA, SUM(PRET*CANTITATE) VAL
FROM COMENZI C JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
WHERE C.ID_CLIENT=P_ID_CLIENT
GROUP BY C.ID_COMANDA, DATA;

BEGIN
    FOR R1 IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE(R1.PRENUME_CLIENT || ': ' || R1.NUME_CLIENT);
        FOR R2 IN C2(R1.ID_CLIENT) LOOP
        DBMS_OUTPUT.PUT_LINE('   ' || R2.ID_COMANDA || '  ' || R2.DATA || ' ' || R2.VAL);
        END LOOP;
    END LOOP;

END;
/


--CURSORUL FOR UPDATE

--FOLOSIND UN CURSOR SA SE MAREASCA CU 5% PRETUL DE LISTA PENTRU PRODUSELE 
--CARE APAR IN CEL PUTIN 5 COMENZI DISTINCTE


SELECT P.ID_PRODUS, DENUMIRE_PRODUS, PRET_LISTA FROM PRODUSE P JOIN RAND_COMENZI R
ON P.ID_PRODUS=R.ID_PRODUS
GROUP BY P.ID_PRODUS, DENUMIRE_PRODUS, PRET_LISTA
HAVING COUNT(*) >=5;

DECLARE
    CURSOR C IS SELECT P.ID_PRODUS, DENUMIRE_PRODUS, PRET_LISTA FROM PRODUSE P 
    WHERE P.ID_PRODUS IN (SELECT R.ID_PRODUS FROM RAND_COMENZI R 
            GROUP BY R.ID_PRODUS
            HAVING COUNT(*) >=5) FOR UPDATE WAIT 10; --SAU NOWAIT
BEGIN
    FOR R IN C LOOP 
    UPDATE PRODUSE SET PRET_LISTA = PRET_LISTA*1.05 WHERE CURRENT OF C;
    DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS || ' ' || R.DENUMIRE_PRODUS || ' ' || R.PRET_LISTA); -- AFISEAZA DATELE DE LA DESCHIDEREA CURSORULUI, NU CELE ACTUALIZATE 
    END LOOP;
    EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('NU AM PUTUT BLOCA RANDURILE PENTRU ACTUALIZARE');
    
END;
/
ROLLBACK;