PL/SQL
    -blocul anonim
    -subprograme stocate(proceduri, functii)
    -pachete
    - declansatori
    
BEGIN
    NULL;
END;
/
 
DECLARE
    --optionala
BEGIN
    --obligatorie
    EXCEPTION
    --optionala
    NULL;
END;
/
    
set serveroutput on
declare
    V_NUME VARCHAR2(100) DEFAULT 'VLAD';
BEGIN


    DBMS_OUTPUT.PUT_LINE('HELLO ' || v_nume);
    V_NUME:='MIHAI';
    DBMS_OUTPUT.PUT_LINE(V_NUME);

END;
/

--SA SE AFISEZE NUMELE SI PRENUMELE ANGAJATULUI 100 FOLOSIND UN BLOC PL/SQL

DECLARE 
    V_NUME ANGAJATI.NUME%TYPE;
    V_PRENUME VARCHAR2(30);
BEGIN
SELECT NUME, PRENUME INTO V_NUME, V_PRENUME FROM ANGAJATI WHERE ID_ANGAJAT=100;
DBMS_OUTPUT.PUT_LINE('Angajat: '  || v_nume || ' ' || v_prenume);
END;
/

DECLARE 
    V_NUME ANGAJATI.NUME%TYPE;
    V_PRENUME VARCHAR2(30);
BEGIN
SELECT NUME, PRENUME INTO V_NUME, V_PRENUME FROM ANGAJATI WHERE ID_ANGAJAT=100;
DBMS_OUTPUT.PUT_LINE('Angajat: '  || v_nume || ' ' || v_prenume);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NU S A GASIT ACEST ANGAJAT');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('S au gasit mai multi angajati');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Au aparut alte exceptii' || SQLERRM);
END;
/

DECLARE
 V_NUME ANGAJATI.NUME%TYPE;
 V_PRENUME CHAR(3);
BEGIN
SELECT NUME,PRENUME INTO V_NUME,V_PRENUME FROM ANGAJATI WHERE ID_ANGAJAT=100;
DBMS_OUTPUT.PUT_LINE('ANGAJAT: '||V_NUME||' '||V_PRENUME);
EXCEPTION
 WHEN NO_DATA_FOUND THEN
       DBMS_OUTPUT.PUT_LINE('NU S A GASIT ACEST ANGAJAT');
       DBMS_OUTPUT.PUT_LINE('CHIAR NU S A GASIT ACEST ANGAJAT');
   WHEN TOO_MANY_ROWS THEN 
       DBMS_OUTPUT.PUT_LINE('S AU GASIT MAI MULTI ANGAJATI');
       DBMS_OUTPUT.PUT_LINE('S AU GASIT MAI MULTI ANGAJATI');
   WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('A APARUT ALTA EXCEPTIE-'||SQLERRM);

END;
/