Declansatori

la nivel de instructiune (1 singura data/instructiune, indiferent cate randuri sunt afectate)
la nivel de rand (1/data pentru fiecare rand afectat)

BEFORE              INSERT         
AFTER               UPDATE         (TABLE)
                    DELETE         
                    
INSTEAD OF         INSERT/UPDATE/DELETE     (VIEW);


/*SA SE CONSTRUIASCA UN TRIGGER CARE NU PERMITE 
ADAUGAREA DE COMENZI DUPA ORA 16:00
MODIFICAREA DE COMENZI DUPA ORA 16:10
STERGEREA DE COMENZI DUPA ORA 16:20*/

CREATE OR REPLACE TRIGGER VERIF_ORA AFTER INSERT OR UPDATE OR DELETE ON COMENZI 
--DECLARE
--  N NUMBER;
BEGIN
  IF INSERTING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:00' THEN
  RAISE_APPLICATION_ERROR(-20000,'NU SE POT ADAUGA COMENZI DUPA ORA 16');
  --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII INSERT');
  ELSIF UPDATING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:10' THEN
  RAISE_APPLICATION_ERROR(-20000,'NU SE POT MODIFICA COMENZI DUPA ORA 16:10');
  --ROLLBACK; COMMIT SI ROLLBACK NU SE FOLOSESC IN INTERIORUL UNUI TRIGGER
  --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII UPDATE');
  ELSIF DELETING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:20' THEN
  RAISE_APPLICATION_ERROR(-20000,'NU SE POT STERGE COMENZI DUPA ORA 16:20');
  --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII DELETE');
  END IF;
END;
/

SET SERVEROUTPUT ON

SELECT * FROM COMENZI WHERE ID_COMANDA>2430;

UPDATE COMENZI SET STARE_COMANDA=STARE_COMANDA+1 WHERE ID_COMANDA > 12330;
DELETE FROM COMENZI WHERE ID_COMANDA>2430;

-- SA SE CONSTRUISCA UN TRIGGER CARE SA PERMITA MAXIM 5 RANDURI IN TABELA REGIUNI

CREATE OR REPLACE TRIGGER MAXIM_REGIUNI AFTER INSERT ON REGIUNI
DECLARE
  N NUMBER;
BEGIN
  SELECT COUNT(*) INTO N FROM REGIUNI;
  IF N>=5 THEN
    RAISE_APPLICATION_ERROR(-20000,'PREA MULTE REGIUNI-'||N);
  END IF;
END;
/

SELECT * FROM REGIUNI;
-- LA TRIGGERI AFTER, MAI INTAI SE DECLANSEAZA RESTR DE INTEGRITATE, DACA ESTE CAZUL
INSERT INTO REGIUNI VALUES(6,'REGIUNEA 6');
  

-- SA SE CONSTRUIASCA UN TRIGGER CARE NU PERMITE MICSORAREA SALARIILOR PENTRU ANG CARE AU INTERMEDIAT
-- CEL PUTIN 2 COMENZI

FOR EACH ROW
            :NEW   :OLD
INSERT       X      NULL
UPDATE       X      X 
DELETE      NULL    X;


CREATE OR REPLACE TRIGGER VERIF_SAL BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE 
  N NUMBER;
BEGIN
   DBMS_OUTPUT.PUT_LINE('SE MODIFICA SALARIUL PENTRU '||:OLD.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);   
   IF :NEW.SALARIUL<:OLD.SALARIUL THEN
     SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
     -- LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL-> MUTATING TRIGGER
     WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
     IF N>=2 THEN
        RAISE_APPLICATION_ERROR(-20001,'NU SE POATE MICSORA SALARIUL PENTRU ACEST ANGAJAT-'||:NEW.ID_ANGAJAT);
     END IF;   
   END IF;
END;
/
-- DACA SE VA DECLANSA EXCEPTIA, NICIUN RAND NU VA FI MODIFICAT
SELECT * FROM COMENZI ORDER BY ID_ANGAJAT;

UPDATE ANGAJATI SET SALARIUL=SALARIUL-5 WHERE ID_ANGAJAT>140;

UPDATE ANGAJATI SET COMISION=COMISION*1.01 WHERE ID_ANGAJAT>180;

SELECT * FROM ANGAJATI WHERE ID_ANGAJAT>140 ORDER BY 1;


CREATE OR REPLACE TRIGGER VERIF_SAL BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE 
  N NUMBER;
BEGIN
   DBMS_OUTPUT.PUT_LINE('SE MODIFICA SALARIUL PENTRU '||:OLD.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);   
   IF :NEW.SALARIUL<:OLD.SALARIUL THEN
     SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
     -- LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL-> MUTATING TRIGGER
     WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
     IF N>=2 THEN
        :NEW.SALARIUL:=:OLD.SALARIUL; -- DOAR PENTRU TRIGGER BEFORE (NU SI PE AFTER)
     END IF;   
   END IF;
END;
/

UPDATE ANGAJATI SET SALARIUL=SALARIUL-5 WHERE ID_ANGAJAT>140;
SELECT * FROM ANGAJATI WHERE ID_ANGAJAT>140 ORDER BY 1;


CREATE OR REPLACE TRIGGER VERIF_SAL BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
WHEN (NEW.SALARIUL<OLD.SALARIUL) -- CAND FOLOSIM NEW SI OLD IN ANTET, NU SE FOLOSESTE :
DECLARE 
  N NUMBER;
BEGIN
   DBMS_OUTPUT.PUT_LINE('SE MODIFICA SALARIUL PENTRU '||:OLD.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);      
     SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
     -- LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL-> MUTATING TRIGGER
     WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
     IF N>=2 THEN
        :NEW.SALARIUL:=:OLD.SALARIUL; -- DOAR PENTRU TRIGGER BEFORE (NU SI PE AFTER)
     END IF;      
END;
/

