--CURSORUL IMPLICIT

NUME_CURSOR%ISOPEN
NUME_CURSOR%FOUND
NUME_CURSOR%NOTFOUND
NUME_CURSOR%ROWCOUNT

SET SERVEROUTPUT ON
--FOLOSIND UN CURSOR SA SE AFISEZE NUMELE SI PRENUMELE CLIENTILOR CARE AU DAT CEL PUTIN DOUA COMENZI
--CLIENTII SE VOR AFISA IN ORDINEA DESC A LIMITEI DE CREDIT

SELECT NUME_CLIENT, PRENUME_CLIENT FROM CLIENTI WHERE ID_CLIENT IN (
SELECT ID_CLIENT FROM COMENZI GROUP BY ID_CLIENT HAVING COUNT(*)>=2);

--PARCURGEREA CLASICA CU OPEN-LOOP-FETCH-CLOSE 

DECLARE 
    CURSOR C IS SELECT NUME_CLIENT, PRENUME_CLIENT, LIMITA_CREDIT FROM CLIENTI WHERE ID_CLIENT IN (
SELECT ID_CLIENT FROM COMENZI GROUP BY ID_CLIENT HAVING COUNT(*)>=2)
    ORDER BY LIMITA_CREDIT DESC;
    V_NUME_CLIENT CLIENTI.NUME_CLIENT%TYPE;
    V_PRENUME_CLIENT CLIENTI.PRENUME_CLIENT%TYPE;
    V_LIMITA_CREDIT CLIENTI.LIMITA_CREDIT%TYPE;
BEGIN 
    IF NOT C%ISOPEN THEN 
        OPEN C;
    END IF;
        LOOP
        FETCH C INTO V_NUME_CLIENT, V_PRENUME_CLIENT, V_LIMITA_CREDIT;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT || ' ' || V_NUME_CLIENT || ' ' || V_PRENUME_CLIENT || ' ' || V_LIMITA_CREDIT);
        END LOOP;
    CLOSE C;
END;
/

DECLARE 
    CURSOR C IS SELECT NUME_CLIENT, PRENUME_CLIENT, LIMITA_CREDIT FROM CLIENTI WHERE ID_CLIENT IN (
SELECT ID_CLIENT FROM COMENZI GROUP BY ID_CLIENT HAVING COUNT(*)>=2)
    ORDER BY LIMITA_CREDIT DESC;

    R C%ROWTYPE;
BEGIN 
    IF NOT C%ISOPEN THEN 
        OPEN C;
    END IF;
        LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT || ' ' || R.NUME_CLIENT || ' ' || R.PRENUME_CLIENT || ' ' || R.LIMITA_CREDIT);
        END LOOP;
    CLOSE C;

END;
/

--FOLOSIND UN CURSOR SA SE AFISEZE NUMELE SI PRENUMELE CLIENTILOR CARE AU DAT CEL PUTIN DOUA COMENZI
--CLIENTII SE VOR AFISA IN ORDINEA DESC A LIMITEI DE CREDIT
--SE VOR AFISA DOAR PRIMII 5 ANGAJATI --DIN SELECT SAU CONDITIA DE IESIRE DIN LOOP, AICI SUNT AMBELE 
-- FETCH FIRST 5 ROWS WITH TIES : II IA SI PE ACEEASI CARE RESPECTA CRIETERIUL DE ORDONARE AL ULTIMULUI LUAT

DECLARE 
    CURSOR C IS SELECT NUME_CLIENT, PRENUME_CLIENT, LIMITA_CREDIT FROM CLIENTI WHERE ID_CLIENT IN (
SELECT ID_CLIENT FROM COMENZI GROUP BY ID_CLIENT HAVING COUNT(*)>=2)
    ORDER BY LIMITA_CREDIT DESC FETCH FIRST 5 ROWS ONLY;

    R C%ROWTYPE;
BEGIN 
    IF NOT C%ISOPEN THEN 
        OPEN C;
    END IF;
        LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND OR C%ROWCOUNT>5;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT || ' ' || R.NUME_CLIENT || ' ' || R.PRENUME_CLIENT || ' ' || R.LIMITA_CREDIT);
        END LOOP;
    CLOSE C;

END;
/



--FOLOSIND UN CURSOR SA SE AFISEZE DENUMIREA DEPARTAMENTELOR UNDE TOTI ANGAJATII AU SALARIILE <=10000

SELECT DENUMIRE_DEPARTAMENT FROM DEPARTAMENTE WHERE ID_DEPARTAMENT IN (SELECT ID_DEPARTAMENT FROM ANGAJATI HAVING MAX(SALARIUL)<=10000 GROUP BY ID_DEPARTAMENT);

DECLARE 
    CURSOR C IS SELECT DENUMIRE_DEPARTAMENT FROM DEPARTAMENTE WHERE ID_DEPARTAMENT IN (SELECT ID_DEPARTAMENT FROM ANGAJATI HAVING MAX(SALARIUL)<=10000 GROUP BY ID_DEPARTAMENT);

    R C%ROWTYPE;
BEGIN 
    IF NOT C%ISOPEN THEN 
        OPEN C;
    END IF;
        LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT || ' ' || R.DENUMIRE_DEPARTAMENT );
        END LOOP;
    CLOSE C;

END;
/

--PARCURGEREA CU FOR

DECLARE 
    CURSOR C IS SELECT DENUMIRE_DEPARTAMENT FROM DEPARTAMENTE WHERE ID_DEPARTAMENT IN (SELECT ID_DEPARTAMENT FROM ANGAJATI HAVING MAX(SALARIUL)<=10000 GROUP BY ID_DEPARTAMENT);

BEGIN 
   /* IF NOT C%ISOPEN THEN 
        OPEN C;
    END IF;*/ -- INAINTE DE PARCURGEREA CU FOR, CURSORUL NU TREBUIE DESCHIS 
    
    --FOR UL inchide si deschide automat cursorul si il declara pe R ca C%ROWTYPE
    FOR R IN C LOOP

        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT || ' ' || R.DENUMIRE_DEPARTAMENT );
        END LOOP;


END;
/



--CURSOR INLINE 

BEGIN 
   /* IF NOT C%ISOPEN THEN 
        OPEN C;
    END IF;*/ -- INAINTE DE PARCURGEREA CU FOR, CURSORUL NU TREBUIE DESCHIS 
    
    --FOR UL inchide si deschide automat cursorul si il declara pe R ca C%ROWTYPE
    FOR R IN (SELECT DENUMIRE_DEPARTAMENT 
                FROM DEPARTAMENTE 
                WHERE ID_DEPARTAMENT IN (
                SELECT ID_DEPARTAMENT 
                FROM ANGAJATI HAVING MAX(SALARIUL)<=10000 
                GROUP BY ID_DEPARTAMENT)) LOOP

        DBMS_OUTPUT.PUT_LINE( R.DENUMIRE_DEPARTAMENT );
        END LOOP;


END;
/


--FOLOSIND UN CURSOR SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR DIN RESPECTIVELE CATEGORII
--SE VOR AFISA DOAR CATEGORIILE CU VALOAR TOTALA A COMENZILOR > 50000

SELECT * FROM PRODUSE;
SELECT * FROM COMENZI;
SELECT * FROM RAND_COMENZI;

SELECT CATEGORIE FROM PRODUSE WHERE ID_PRODUS IN (SELECT ID_PRODUS FROM RAND_COMENZI HAVING(SUM(PRET*CANTITATE)>50000) GROUP BY ID_PRODUS);



DECLARE 
CURSOR C IS SELECT CATEGORIE FROM PRODUSE P, RAND_COMENZI R WHERE P.ID_PRODUS=R.ID_PRODUS IN (SELECT ID_PRODUS FROM RAND_COMENZI HAVING(SUM(PRET*CANTITATE)>50000) GROUP BY ID_PRODUS);
BEGIN
    FOR R IN C LOOP
    DBMS_OUTPUT.PUT_LINE( R.CATEGORIE);
    END LOOP;
END;
/







