ERORI 

-COMPILATION TIME ERRORS

-RUNTIME ERRORS
EXCEPTII
    - IMPLICITE
        - PREDEFINITE: NO_DATA_FOUND, TOO_MANY_ROWS, DUP_VAL_ON_INDEX, INVALID_CURSOR...
        - NON-PREDEFINITE: AU COD DE EXCEPTIE DAR NU AU SI HANDLER-UL DE EXCEPTIE
    -EXPLICITE
        - DEFINITE DE UTILIZATOR
        
DECLARE 
    I NUMBER(3);
    CURSOR C IS SELECT * FROM ANGAJATI;
    R C%ROWTYPE;
BEGIN
--RAISE CURSOR_ALREADY_OPEN;
I:=100;
I:=I/0;
--FETCH C INTO R;
    EXCEPTION
        WHEN ZERO_DIVIDE THEN
            BEGIN
                DBMS_OUTPUT.PUT_LINE('NU PUTEM IMPARTI LA 0');
            FETCH C INTO R;
            EXCEPTION WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('EXCEPTIE IN EXCEPTIE');
            END;
        WHEN INVALID_CURSOR OR VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('CURSORUL NU A FOST DESCHIS SAU VARIABILA ARE O DIM PREA MICA');
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE');
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;
/


DECLARE 
    ESTE_MANAGER EXCEPTION;
    PRAGMA EXCEPTION_INIT(ESTE_MANAGER, -02292);
BEGIN
    DELETE FROM ANGAJATI WHERE ID_ANGAJAT=100;
    EXCEPTION 
        WHEN ESTE_MANAGER THEN
        DBMS_OUTPUT.PUT_LINE('NU POT STERGE ANGAJATUL, SE INCALCA UN FK');

END;
/

--FOLOSIND O EXCEPTIE SA SE REZOLVE URMATOARE CERINTA
--SA SE ADAUGE UN ANGAJAT CU ID-UL CITIT DE LA TASTATURA SI SALARIUL CITIT DE LA TASTATURA
--DACA ANAGAJATUL EXISTA, I SE VA MODIFICA CU CEL CITIT
select * from angajati WHERE ID_ANGAJAT=340;
SELECT * FROM ANGAJATI WHERE ID_ANGAJAT=100;
SELECT * FROM ANGAJATI;


ACCEPT ID PROMPT "INTRODUCETI ID-UL ANGAJATULUI:"
ACCEPT SALARIU PROMPT "INTRODUCETI SALARIUL ANGAJATULUI:"
DECLARE 
    ID NUMBER;
    SALARIU NUMBER;
    DEJA_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(DEJA_EXISTA, -1);
BEGIN
    INSERT INTO ANGAJATI VALUES (&ID, null, 'ABCD', 'NKOCHARR', NULL, SYSDATE-30, 'IT_PROG', &SALARIU, NULL, NULL, NULL); 
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            UPDATE angajati 
            SET salariul=&SALARIU
            WHERE id_angajat=&ID;
            DBMS_OUTPUT.PUT_LINE('ANGAJATUL DEJA EXISTA');

END;
/

--SA SE CONSTRUIASCA TABELA PERSOANE(ID_PERSOANA, NUME, PRENUME)
--DACA TABELA EXISTA, SA SE STEARGA TABELA PERSOANA


DECLARE
    TABELA_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(TABELA_EXISTA, -955);
BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE PERSOANE(ID_PERS NUMBER, NUME VARCHAR2(30), PRENUME VARCHAR2(30))';
    DBMS_OUTPUT.PUT_LINE('AM CREAT TABELA ');
    EXECUTE IMMEDIATE 'INSERT INTO PERSOANE VALUES(1, ''POPESCU'', ''MARIUS'')';
    EXCEPTION WHEN TABELA_EXISTA THEN 
        EXECUTE IMMEDIATE 'DROP TABLE PERSOANE';
        DBMS_OUTPUT.PUT_LINE('AM STERS TABELA');

END;
/


SELECT * FROM PERSOANE;