SET SERVEROUTPUT ON

CREATE OR REPLACE PACKAGE MYPACK_1061 IS
 V_COTA NUMBER(2):=21;
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER);
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER, N3 NUMBER); -- PUTEM SUPRAINCARCA FUNCTII SI PROCEDURI IN INTERIORUL PACHETULUI
 FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER;
END;
/
-- IN BODY TREBUIE SA IMPLEMENTEZ CEL PUTIN FUNCTIILE SI PROCEDURILE DIN SPEC
-- SE POT CONSTRUI SI ALTE FUNCTII SI PROCEDURI PRIVATE (POT FI APELATE DOAR DE ALTE FUNCTII SI PROC DIN PACHET)
CREATE OR REPLACE PACKAGE BODY MYPACK_1061 IS
 V_COTA NUMBER(2);
 
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER) IS
 BEGIN
   DBMS_OUTPUT.PUT_LINE('SUMA ESTE '||(N1+N2));
 END;
 
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER, N3 NUMBER) IS
 BEGIN
   DBMS_OUTPUT.PUT_LINE('SUMA ESTE '||(N1+N2+N3));  
   
 END;
 -- O FUNCTIE SAU O PROCEDURA PRIVATA POATE FI APELATA IN ACELASI DAR DOAR DE O FCT SAU PROC CARE-I URMEAZA
 -- FORWARD DECLARATION
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER, N3 NUMBER, N4 NUMBER) IS
 BEGIN
   DBMS_OUTPUT.PUT_LINE('SUMA ESTE '||(N1+N2+N3+N4));
 END;
  
 FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER IS
 BEGIN
   ADD_NUMBERS(10,25,25,170);
   RETURN N1*N2;
 END;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('COTA='||MYPACK_1061.V_COTA);
  MYPACK_1061.V_COTA:=27;
  DBMS_OUTPUT.PUT_LINE('COTA='||MYPACK_1061.V_COTA);
  MYPACK_1061.ADD_NUMBERS(10,25);
  MYPACK_1061.ADD_NUMBERS(10,25,25);
  --MYPACK_1061.ADD_NUMBERS(10,25,25,17);
  DBMS_OUTPUT.PUT_LINE(MYPACK_1061.MULTIPLY_NUMBERS(15,17));
END;
/


SA SE CONSTRUIASCA UN PACHET CARE CONTINE

O FUNCTIE CARE PRIMESTE CA PARAMETRUL ID-UL UNUI PRODUS SI UN AN CALENDARISTIC (E.G 2019)
   FUNCTIA VA RETURNA VALOAREA TOTALA PENTRU COMENZILE PROD RESEPCTIV IN ANUL RESPECTIV
O PROCEDURA CARE APELEAZA FUNCTIA DINTR-UN CURSOR. PROCEDURA VA DECLANSA O EXCEPTIE DEF DE UTILIZATOR
EXCEPTIA SE VA DECLANSA DACA VAL COMENZILOR PENTRU ACEL AN<500.000
SA SE APLEZE PROCEDURA DINTR-UN BLOC ANONIN. SA SE TRATEZE EXCEPTIA FARA A FOLOSI OTHERS

CREATE OR REPLACE PACKAGE PACK_COMENZI IS
  
  VAL_MICA EXCEPTION;
  PRAGMA EXCEPTION_INIT(VAL_MICA,-20001);
  
  FUNCTION GET_VAL_PROD_AN(P_ID_PRODUS NUMBER, P_AN NUMBER) RETURN NUMBER;
  PROCEDURE ARATA_COM(P_AN NUMBER, P_VAL NUMBER DEFAULT 200000);
END;
/

CREATE OR REPLACE PACKAGE BODY PACK_COMENZI IS
  FUNCTION GET_VAL_PROD_AN(P_ID_PRODUS NUMBER, P_AN NUMBER) RETURN NUMBER IS
    V_VAL NUMBER;
  BEGIN
    SELECT SUM(PRET*CANTITATE) INTO V_VAL FROM COMENZI C JOIN RAND_COMENZI R
      ON C.ID_COMANDA=R.ID_COMANDA WHERE EXTRACT(YEAR FROM DATA)=P_AN AND R.ID_PRODUS=P_ID_PRODUS;
    RETURN NVL(V_VAL,0);  
  END;
  -- SE VA DECLAMSA IN PROCEDURA O EXCEPTIE DACA VAL COMENZILOR PENTRU ACEL AN<P_VAL
  PROCEDURE ARATA_COM(P_AN NUMBER, P_VAL NUMBER DEFAULT 200000) IS
    CURSOR C IS SELECT ID_PRODUS,DENUMIRE_PRODUS,GET_VAL_PROD_AN(ID_PRODUS,P_AN) VAL
      FROM PRODUSE 
      WHERE GET_VAL_PROD_AN(ID_PRODUS,P_AN)>0 ORDER BY VAL DESC;      
    R C%ROWTYPE; 
    V_SUMA NUMBER DEFAULT 0;
  BEGIN
   OPEN C;
   LOOP
     FETCH C INTO R;
     EXIT WHEN C%NOTFOUND;
     DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.VAL);
     V_SUMA:=V_SUMA+R.VAL;
   END LOOP;
   CLOSE C;
   DBMS_OUTPUT.PUT_LINE('SUMA='||V_SUMA);
   IF V_SUMA<P_VAL THEN
     RAISE_APPLICATION_ERROR(-20001,'SUMA TOTALA ESTE MAI MICA DECAT '||P_VAL||', ESTE '||V_SUMA);
   END IF;   
  END;  
END;
/
 -- EXCEPTIILE POT FI DECLARATE SI ASOCIATE CU UN COD DE EXCEPTIE SI IN PARTEA PUBLICA A UNUI PACHET
BEGIN
  PACK_COMENZI.ARATA_COM(2024,700000);
  EXCEPTION
    WHEN PACK_COMENZI.VAL_MICA THEN
      DBMS_OUTPUT.PUT_LINE('EXCEPTIA: '||SQLERRM);
END;
/



SELECT * FROM COMENZI;
 