/*-RUNTIME ERRORS
EXCEPTII
    - IMPLICITE
        - PREDEFINITE: NO_DATA_FOUND, TOO_MANY_ROWS, DUP_VAL_ON_INDEX, INVALID_CURSOR...
        - NON-PREDEFINITE: AU COD DE EXCEPTIE DAR NU AU SI HANDLER-UL DE EXCEPTIE
    -EXPLICITE
        - DEFINITE DE UTILIZATOR
*/    

/*
    INTERVALUL DE CODURI PT EXCEPTILE DEFINITE DE UTILIZATOR ESTE
    [-20999, -20000]

*/
SET SERVEROUTPUT ON
DECLARE 
    ESTE_CHEIE_EXTERNA EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(ESTE_CHEIE_EXTERNA, -2292);
    PRAGMA EXCEPTION_INIT(NU_EXISTA, -20000);
BEGIN 
    DELETE FROM PRODUSE WHERE ID_PRODUS>35000;
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000, 'NU EXISTA PRODUSUL'); --VARIANTA RECOMANDATA PENTRU A DECLANSA EXCEPTII DEFINITE DE UTILIZATOR --SE POT DECLANSA SI EXCEPTII PREDEFINITE
        DBMS_OUTPUT.PUT_LINE('NU S-A STERS NICIUN PRODUS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('S-AU STERS ' || SQL%ROWCOUNT || ' PRODUSE');
    END IF;
    EXCEPTION
        WHEN ESTE_CHEIE_EXTERNA THEN
            DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE PRODUSUL, SE INCALCA UN FK');
    --UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA+100 WHERE ID_PRODUS=90001;
        WHEN NU_EXISTA THEN 
             DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA: ' || SQLERRM);
END;
/



SELECT * FROM PRODUSE WHERE ID_PRODUS NOT IN (SELECT ID_PRODUS FROM RAND_COMENZI) ORDER BY 1;


--PROCEDURI SI FUNCTII

CREATE OR REPLACE PROCEDURE STERGE_PRODUS IS 
    ESTE_CHEIE_EXTERNA EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(ESTE_CHEIE_EXTERNA, -2292);
    PRAGMA EXCEPTION_INIT(NU_EXISTA, -20000);
BEGIN 
    DELETE FROM PRODUSE WHERE ID_PRODUS>35000;
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000, 'NU EXISTA PRODUSUL'); --VARIANTA RECOMANDATA PENTRU A DECLANSA EXCEPTII DEFINITE DE UTILIZATOR --SE POT DECLANSA SI EXCEPTII PREDEFINITE
        DBMS_OUTPUT.PUT_LINE('NU S-A STERS NICIUN PRODUS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('S-AU STERS ' || SQL%ROWCOUNT || ' PRODUSE');
    END IF;
    EXCEPTION
        WHEN ESTE_CHEIE_EXTERNA THEN
            DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE PRODUSUL, SE INCALCA UN FK');
    --UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA+100 WHERE ID_PRODUS=90001;
       /* WHEN NU_EXISTA THEN 
             DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA: ' || SQLERRM); */
END;
/

EXEC STERGE_PRODUS; --APEL TIP PL/SQL
CALL STERGE_PRODUS(); --APEL TIP SQL

--DACA O EXCEPTIE NU ESTE TRATATA IN SUBPROGRAM ATUNCI EA ESTE PROPAGATA BLOCULUI APELATOR CARE POATE LA RANDUL SAU SA O TRATEZE
DECLARE 
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA, -20000);
BEGIN 
    STERGE_PRODUS;   --APELEZ PROCEDURA DINTR-UN BLOC ANONIM
    EXCEPTION WHEN NU_EXISTA THEN 
             DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA: ' || SQLERRM);
END;
/

SUBPROGRAMELE POT AVEA PARAMETRII
IN (VAR IMPLICITA)
OUT
IN OUT

--SA SE MODIFICE PROCEDURA A.I. SA SE AFISEZE SI PRETUL NOU
CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD(P_ID_PRODUS NUMBER, P_PROCENT NUMBER) IS
    CURSOR C IS SELECT PRET_LISTA FROM PRODUSE WHERE ID_PRODUS=P_ID_PRODUS;
    R C%ROWTYPE;
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS = P_ID_PRODUS;
    OPEN C;
    FETCH C INTO R;
    DBMS_OUTPUT.PUT_LINE(R.PRET_LISTA);
END;
/

SELECT ID_PRODUS, DENUMIRE_PRODUS, PRET_LISTA FROM PRODUSE WHERE ID_PRODUS=2378;


EXEC MARESTE_PRET_PROD2(5378, 10);

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD2(P_ID_PRODUS NUMBER, P_PROCENT NUMBER) IS
    V_PRET NUMBER;
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS = P_ID_PRODUS
    RETURNING PRET_LISTA INTO V_PRET;
    IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE: ' || V_PRET);
    END IF;
END;
/
CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER, P_PROCENT NUMBER, P_PRET_NOU OUT NUMBER) IS
    V_PRET NUMBER;
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS = P_ID_PRODUS
    RETURNING PRET_LISTA INTO P_PRET_NOU;
END;
/

DECLARE 
    P NUMBER;
BEGIN
    MARESTE_PRET_PROD3(2378, 10, P);
    IF P IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE: ' || P);
    END IF;
END;
/








