

set serveroutput on

DECLARE 
    V_NUME ANGAJATI.NUME%TYPE;
    V_PRENUME VARCHAR2(30);
    V_TAXE CONSTANT NUMBER:=0.19; --CONSTANTELE TREBUIE INITIALIZATE
BEGIN
SELECT NUME, PRENUME INTO V_NUME, V_PRENUME FROM ANGAJATI WHERE ID_ANGAJAT=100;
DBMS_OUTPUT.PUT_LINE('Angajat: '  || V_NUME || ' ' ||V_PRENUME);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE' || SQLERRM);
END;
/


DECLARE 
    V_NUME ANGAJATI.NUME%TYPE;
    V_PRENUME VARCHAR2(30);
BEGIN
SELECT NUME, PRENUME INTO V_NUME, V_PRENUME FROM ANGAJATI WHERE ID_ANGAJAT=100;
DBMS_OUTPUT.PUT_LINE('Angajat: '  || v_nume || ' ' || v_prenume);
END;
/


DECLARE
    V_ANG ANGAJATI%ROWTYPE;
BEGIN
    select * into v_ang from angajati where id_angajat=101;
    DBMS_OUTPUT.PUT_LINE(V_ANG.ID_ANGAJAT || ' ' || V_ANG.NUME || ' ' || V_ANG.PRENUME || ' ' || V_ANG.SALARIUL);
END;
/

/*STRUCTURILE FUNDAMENTALE DE PROGRAM
- SECVENTIALA 
-ALTERNATIVA
    - IF -ELSIF - ELSE END
    - CASE -END CASE
-REPETITIVA
    - CU NR CUNOSCUT DE PASI: FOR
    - CU NR NECUNPSCUT DE PASI: WHILE, SI LOOP
    
*/

DECLARE
    V_NOTA NUMBER(2) := 10;
BEGIN
IF V_NOTA IS NULL  THEN 
    DBMS_OUTPUT.PUT_LINE('NOTA LIPSA');
ELSIF V_NOTA<1 OR V_NOTA>10 THEN
    DBMS_OUTPUT.PUT_LINE('NOTA ERONATA');
ELSIF V_NOTA < 5 THEN
    DBMS_OUTPUT.PUT_LINE('PICAT');
ELSIF V_NOTA=10 THEN
    DBMS_OUTPUT.PUT_LINE('NOTA 10');
ELSE DBMS_OUTPUT.PUT_LINE('PROMOVAT');
END IF;
END;
/

DECLARE
    V_NOTA NUMBER(2) := 8;
BEGIN
CASE
WHEN V_NOTA IS NULL  THEN 
    DBMS_OUTPUT.PUT_LINE('NOTA LIPSA');
WHEN  V_NOTA<1 OR V_NOTA>10 THEN
    DBMS_OUTPUT.PUT_LINE('NOTA ERONATA');
WHEN V_NOTA < 5 THEN
    DBMS_OUTPUT.PUT_LINE('PICAT');
WHEN V_NOTA=10 THEN
    DBMS_OUTPUT.PUT_LINE('NOTA 10');
--ELSE DBMS_OUTPUT.PUT_LINE('PROMOVAT');
END CASE;
EXCEPTION WHEN CASE_NOT_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('FELICITARI');
END;
/

DECLARE 
I NUMBER:=5;
BEGIN
    FOR I IN 25..35 LOOP --SE POT SI VARIABILE IN INTERVAL
        CONTINUE WHEN I mod 2 = 1;
        DBMS_OUTPUT.PUT_LINE('I='||I);
        --EXIT WHEN I=30;

    END LOOP;
    DBMS_OUTPUT.PUT_LINE('I='||I);
    --EXCEPTION WHEN OTHERS THEN  NULL;
END;
/

DECLARE
I NUMBER:=25;
BEGIN
    WHILE (I<35) LOOP
    DBMS_OUTPUT.PUT_LINE('I='||I);
    I:=I+1;
    END LOOP;
END;
/

DECLARE
I PLS_INTEGER:=25;
BEGIN
    LOOP
    DBMS_OUTPUT.PUT_LINE('I='||I);
    I:=I+1;
    EXIT WHEN I>35;
    END LOOP;
END;

