SET SERVEROUTPUT ON
DECLARE
  V VARCHAR2(50):='980374230957823905';
  N PLS_INTEGER;
BEGIN
  FOR I IN REVERSE 1..LENGTH(V) LOOP
    N:=SUBSTR(V,I,1);
    DBMS_OUTPUT.PUT(N);
  END LOOP;  
  DBMS_OUTPUT.NEW_LINE;
END;
/

DECLARE
  V VARCHAR2(50):='9803742A30C957#823*905';
  V_SUMA_PARE PLS_INTEGER:=0;
  V_SUMA_IMPARE PLS_INTEGER DEFAULT 0;
  N PLS_INTEGER;
BEGIN
  FOR I IN 1..LENGTH(V) LOOP
    IF ASCII(SUBSTR(V,I,1)) BETWEEN 49 AND 57 THEN      
    N:=SUBSTR(V,I,1);
    IF N MOD 2=0 THEN
      V_SUMA_PARE:=V_SUMA_PARE+N;
    ELSE   
      V_SUMA_IMPARE:=V_SUMA_IMPARE+N;
    END IF;  
    END IF;
  END LOOP;  
  DBMS_OUTPUT.PUT_LINE('PARE='||V_SUMA_PARE);
  DBMS_OUTPUT.PUT_LINE('IMPARE='||V_SUMA_IMPARE);
END;
/
SET DEFINE OFF
DECLARE
  V VARCHAR2(50):='9803742A&30C957#823*905';
  V_SUMA_PARE PLS_INTEGER:=0;
  V_SUMA_IMPARE PLS_INTEGER DEFAULT 0;
  N PLS_INTEGER;
BEGIN
  FOR I IN 1..LENGTH(V) LOOP
    IF SUBSTR(V,I,1) BETWEEN '1' AND '9' THEN      
    N:=SUBSTR(V,I,1);
    IF N MOD 2=0 THEN
      V_SUMA_PARE:=V_SUMA_PARE+N;
    ELSE   
      V_SUMA_IMPARE:=V_SUMA_IMPARE+N;
    END IF;  
    END IF;
  END LOOP;  
  DBMS_OUTPUT.PUT_LINE('PARE='||V_SUMA_PARE);
  DBMS_OUTPUT.PUT_LINE('IMPARE='||V_SUMA_IMPARE);
END;
/

 SA SE AFISEZE PRODUSELE CU ID-UL INTRE 1726 SI 1740
 SE VA AFISA ID-UL, DENUMIREA SI CATEGORIA 
SELECT * FROM PRODUSE ORDER BY 1;

DECLARE
  V_ID_PRODUS PRODUSE.ID_PRODUS%TYPE;
  V_DENUMIRE_PRODUS PRODUSE.DENUMIRE_PRODUS%TYPE;
  V_CATEGORIE PRODUSE.CATEGORIE%TYPE;
BEGIN
  FOR I IN 1726..1740 LOOP
   BEGIN
    SELECT ID_PRODUS, DENUMIRE_PRODUS,CATEGORIE INTO
     V_ID_PRODUS,V_DENUMIRE_PRODUS,V_CATEGORIE
     FROM PRODUSE WHERE ID_PRODUS=I;
     DBMS_OUTPUT.PUT_LINE(V_ID_PRODUS||' '||V_DENUMIRE_PRODUS||' '||V_CATEGORIE);
     EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
   END;  
  END LOOP;  
END;
/
  
DECLARE
  V_ID_PRODUS PRODUSE.ID_PRODUS%TYPE;
  V_DENUMIRE_PRODUS PRODUSE.DENUMIRE_PRODUS%TYPE;
  V_CATEGORIE PRODUSE.CATEGORIE%TYPE;
  N PLS_INTEGER;
BEGIN
  FOR I IN 1726..1740 LOOP
    SELECT COUNT(*) INTO N FROM PRODUSE WHERE ID_PRODUS=I;
    IF N=1 THEN
    SELECT ID_PRODUS, DENUMIRE_PRODUS,CATEGORIE INTO
     V_ID_PRODUS,V_DENUMIRE_PRODUS,V_CATEGORIE
     FROM PRODUSE WHERE ID_PRODUS=I;
     DBMS_OUTPUT.PUT_LINE(V_ID_PRODUS||' '||V_DENUMIRE_PRODUS||' '||V_CATEGORIE);
   END IF;     
  END LOOP;  
END;
/
  
DECLARE
  V PRODUSE%ROWTYPE;
  N PLS_INTEGER;
BEGIN
  FOR I IN 1726..1740 LOOP
    SELECT COUNT(*) INTO N FROM PRODUSE WHERE ID_PRODUS=I;
    IF N=1 THEN
    SELECT * INTO V
     FROM PRODUSE WHERE ID_PRODUS=I;
     DBMS_OUTPUT.PUT_LINE(V.ID_PRODUS||' '||V.DENUMIRE_PRODUS||' '||V.CATEGORIE);
   END IF;     
  END LOOP;  
END;
/

DECLARE
  TYPE T_REC IS RECORD(
     ID_PRODUS PRODUSE.ID_PRODUS%TYPE,
     DENUMIRE_PRODUS PRODUSE.DENUMIRE_PRODUS%TYPE,
     CATEGORIE PRODUSE.CATEGORIE%TYPE
  );
  V T_REC;
  N PLS_INTEGER;
BEGIN
  FOR I IN 1726..1740 LOOP
    SELECT COUNT(*) INTO N FROM PRODUSE WHERE ID_PRODUS=I;
    IF N=1 THEN
    SELECT ID_PRODUS, DENUMIRE_PRODUS,CATEGORIE INTO V
     FROM PRODUSE WHERE ID_PRODUS=I;
     DBMS_OUTPUT.PUT_LINE(V.ID_PRODUS||' '||V.DENUMIRE_PRODUS||' '||V.CATEGORIE);
   END IF;     
  END LOOP;  
END;
/


SET SERVEROUTPUT ON
DECLARE
TYPE EmpTabTyp IS TABLE OF angajati%ROWTYPE INDEX BY PLS_INTEGER;
emp_tab EmpTabTyp;
BEGIN
SELECT * INTO emp_tab(200) FROM angajati WHERE id_angajat = 200;
dbms_output.put_line('Nume='||emp_tab(200).prenume);
dbms_output.put_line(case when emp_tab.exists(200) then 'exista' else 'nu exista' end);
dbms_output.put_line(case when emp_tab.exists(1) then 'exista' else 'nu exista' end);
SELECT * INTO emp_tab(205) FROM angajati WHERE id_angajat = 205;
dbms_output.put_line('Nume='||emp_tab(205).prenume);
dbms_output.put_line('Numar de elemente='||emp_tab.count);
emp_tab(122):=emp_tab(205);
dbms_output.put_line('Nume='||emp_tab(122).prenume);
dbms_output.put_line('Numar de elemente='||emp_tab.count);
emp_tab(2005).prenume:='John';
dbms_output.put_line('Numar de elemente='||emp_tab.count);
END;
/
DELETE FROM ANGAJATI WHERE ID_ANGAJAT=110;
set serveroutput on
DECLARE
TYPE tab_ind IS TABLE OF angajati%ROWTYPE INDEX BY PLS_INTEGER;
t tab_ind;
BEGIN
SELECT * BULK COLLECT INTO t FROM angajati order by salariul desc;
DBMS_OUTPUT.PUT_LINE('Numar de elemente '||t.COUNT);
t.delete(10);
DBMS_OUTPUT.PUT_LINE('Numar de elemente '||t.COUNT);
FOR i IN t.first.. t.LAST LOOP
    CONTINUE WHEN NOT T.EXISTS(I);
    DBMS_OUTPUT.PUT_LINE(t(i).prenume ||' '||t(i).nume ||'->'||i);
END LOOP;
END;
/


