SET SERVEROUTPUT ON
DECLARE
  TYPE T_COL IS TABLE OF VARCHAR2(100) INDEX BY VARCHAR2(100);
  V T_COL;
  I VARCHAR2(100);
BEGIN
  V('ALINA'):='BUCURESTI';
  V('MARIA'):='BUCURESTI';
  V('PETRU'):='CONSTANTA';
  V('ADELA'):='ALBA IULIA';
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);--||' DOMICILIU='||V(V.LAST));  
  I:=V.FIRST;
  WHILE I IS NOT NULL LOOP
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));
    I:=V.NEXT(I);
   --I:=V.NEXT('ADELA'); I:='ALINA'
  END LOOP;
END;
/

/*15- 12:30->15:40 2013 A SI B
17 - 10:50->14 2016
18 - 10:50 -> 2017+2209 7:30->10:40*/

SELECT * FROM CLIENTI;

FOLOSIND UN BLOC PL/SQL, SA SE AFISEZE NUMELE CLIENTILOR CARE
AU DAT CEL PUTIN 1 COMANDA
CLIENTII VOR FI AFISATI DESC DUPA LIMITA DE CREDIT

SELECT * FROM CLIENTI WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
AND LIMITA_CREDIT>300
ORDER BY LIMITA_CREDIT DESC;

DECLARE
  TYPE T_CLIENT IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
  V T_CLIENT;
  I PLS_INTEGER;
BEGIN
  SELECT NUME_CLIENT BULK COLLECT INTO V FROM CLIENTI 
    WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
    ORDER BY LIMITA_CREDIT DESC;
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);  
  I:=V.FIRST;
  WHILE I IS NOT NULL LOOP
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));
    I:=V.NEXT(I);   
  END LOOP;
END;
/

DECLARE
  TYPE T_CLIENT IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
  V T_CLIENT;  
BEGIN
  SELECT NUME_CLIENT BULK COLLECT INTO V FROM CLIENTI 
    WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
    AND LIMITA_CREDIT>300
    ORDER BY LIMITA_CREDIT DESC;
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);  
  --V(1):='JOHN DOE';
  --V.DELETE(7,10);
  FOR I IN 1..V.COUNT LOOP
   --CONTINUE WHEN NOT V.EXISTS(I); 
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));    
  END LOOP;
END;
/

DECLARE
  TYPE T_CLIENT IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
  V T_CLIENT;  
BEGIN
  SELECT NUME_CLIENT||' '||PRENUME_CLIENT||' '||LIMITA_CREDIT
  BULK COLLECT INTO V FROM CLIENTI 
    WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
    AND LIMITA_CREDIT>300
    ORDER BY LIMITA_CREDIT DESC;
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);  
  --V(1):='JOHN DOE';
  --V.DELETE(7,10);
  FOR I IN 1..V.COUNT LOOP
   --CONTINUE WHEN NOT V.EXISTS(I); 
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));    
  END LOOP;
END;
/

DECLARE
  TYPE T_CLIENT IS TABLE OF CLIENTI%ROWTYPE INDEX BY PLS_INTEGER;
  V T_CLIENT;  
BEGIN
  SELECT *
  BULK COLLECT INTO V FROM CLIENTI 
    WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
    AND LIMITA_CREDIT>300
    ORDER BY LIMITA_CREDIT DESC;
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);  
  FOR I IN 1..V.COUNT LOOP  
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I).NUME_CLIENT||' '||V(I).PRENUME_CLIENT||
     ' '||V(I).LIMITA_CREDIT);    
  END LOOP;
END;
/

DECLARE
  TYPE T_REC IS RECORD(
    NUME_CLIENT CLIENTI.NUME_CLIENT%TYPE,
    PRENUME_CLIENT CLIENTI.PRENUME_CLIENT%TYPE,
    LIMITA_CREDIT CLIENTI.LIMITA_CREDIT%TYPE
  );
  TYPE T_CLIENT IS TABLE OF T_REC INDEX BY PLS_INTEGER;
  V T_CLIENT;  
BEGIN
  SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
  BULK COLLECT INTO V FROM CLIENTI 
    WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
    AND LIMITA_CREDIT>300
    ORDER BY LIMITA_CREDIT DESC;
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);  
  FOR I IN 1..V.COUNT LOOP  
   DBMS_OUTPUT.PUT_LINE(I||'->'||V(I).NUME_CLIENT||' '||V(I).PRENUME_CLIENT||
     ' '||V(I).LIMITA_CREDIT);    
  END LOOP;
  V.DELETE;
  DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
  DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST);
  DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST);  
END;
/

