CREATE OR REPLACE TRIGGER secure_emp BEFORE
INSERT OR UPDATE OR DELETE ON angajati 
BEGIN
 IF INSERTING THEN
  DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL LA UN INSERT');
 ELSIF UPDATING THEN
 DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL LA UN UPDATE');
 ELSIF DELETING THEN
 DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL LA UN DELETE');
 END IF;
END;
/

SET SERVEROUTPUT ON

UPDATE ANGAJATI SET SALARIUL=SALARIUL+100 WHERE ID_DEPARTAMENT=500;

DELETE FROM ANGAJATI WHERE ID_DEPARTAMENT=500;


CREATE OR REPLACE TRIGGER secure_emp BEFORE
INSERT OR UPDATE OR DELETE ON angajati 
BEGIN
 IF (TO_CHAR(SYSDATE,'DY') IN ('SAT','SUN')) OR  (TO_CHAR(SYSDATE,'HH24') 
       NOT BETWEEN '07' AND '08') THEN
   IF DELETING THEN RAISE_APPLICATION_ERROR(-20502,'You may delete from EMPLOYEES table 
     only during business hours.');
   ELSIF INSERTING THEN RAISE_APPLICATION_ERROR(-20500,'You may insert into EMPLOYEES table only during business hours.');
   ELSIF UPDATING('SALARIUL') THEN
    RAISE_APPLICATION_ERROR(-20503, 'You may update SALARY only during business hours.');
   ELSE RAISE_APPLICATION_ERROR(-20504,'You may update EMPLOYEES table only during normal hours.');
   END IF;
 END IF;
END;
/


UPDATE ANGAJATI SET SALARIUL=-100 WHERE ID_ANGAJAT>150;

UPDATE ANGAJATI SET SALARIUL=SALARIUL+50 WHERE ID_DEPARTAMENT=50;
UPDATE ANGAJATI SET COMISION=COMISION+1 WHERE ID_DEPARTAMENT=500;






SELECT TO_CHAR(SYSDATE,'HH24') FROM DUAL;
SELECT * FROM ANGAJATI WHERE ID_DEPARTAMENT=50;

SELECT ID_PRODUS,DENUMIRE_PRODUS,PRET_LISTA FROM PRODUSE;

-- SA SE CONSTRUIASCA UN TRIGER CARE SA NU PERMITA
-- SCADEREA PRETULUI PENTRU PRODUSELE CU O VALOARE TOTAL COMANDATA MAI MARE DE 5000
CREATE OR REPLACE TRIGGER VERIF_PRODUSE
BEFORE UPDATE OF PRET_LISTA ON PRODUSE
FOR EACH ROW
DECLARE
  V_VAL NUMBER;
BEGIN
 DBMS_OUTPUT.PUT_LINE('SE REALIZEAZA O MODIFICARE PENTRU PROD '||:OLD.ID_PRODUS||', 
       se schimba pretul din '||:OLD.PRET_LISTA||' IN '||:NEW.PRET_LISTA);  
 IF :NEW.PRET_LISTA<:OLD.PRET_LISTA THEN
 SELECT NVL(SUM(PRET*CANTITATE),0) INTO V_VAL
 FROM RAND_COMENZI WHERE ID_PRODUS=:NEW.ID_PRODUS; 
 IF V_VAL > 5000 THEN
 DBMS_OUTPUT.PUT_LINE('VAL COMENZI: '||V_VAL);
 RAISE_APPLICATION_ERROR(-20000,'NU SE POATE MICSORA PRETUL DE LISTA PENTRU '||:NEW.ID_PRODUS);      
 END IF;
 END IF;      
END;
/

CREATE OR REPLACE TRIGGER VERIF_PRODUSE
BEFORE UPDATE OF PRET_LISTA ON PRODUSE
FOR EACH ROW
WHEN (NEW.PRET_LISTA<OLD.PRET_LISTA)
DECLARE
  V_VAL NUMBER;
BEGIN
 DBMS_OUTPUT.PUT_LINE('SE REALIZEAZA O MODIFICARE PENTRU PROD '||:OLD.ID_PRODUS||', 
       se schimba pretul din '||:OLD.PRET_LISTA||' IN '||:NEW.PRET_LISTA); 
 -- NU FOLOSIM OPERATII LMD PE TABELA PE CARE AM DECLARAT TRIGGER FOR EACH ROW        
 SELECT NVL(SUM(PRET*CANTITATE),0) INTO V_VAL
 FROM RAND_COMENZI R
 --JOIN PRODUSE P ON R.ID_PRODUS=P.ID_PRODUS
 WHERE R.ID_PRODUS=:NEW.ID_PRODUS; 
 IF V_VAL > 5000 THEN
 DBMS_OUTPUT.PUT_LINE('VAL COMENZI: '||V_VAL);
 RAISE_APPLICATION_ERROR(-20000,'NU SE POATE MICSORA PRETUL DE LISTA PENTRU '||:NEW.ID_PRODUS);       
 END IF;      
END;
/
CREATE OR REPLACE TRIGGER VERIF_PRODUSE
BEFORE UPDATE OF PRET_LISTA ON PRODUSE
FOR EACH ROW
WHEN (NEW.PRET_LISTA<OLD.PRET_LISTA)
DECLARE
  V_VAL NUMBER;
BEGIN
 DBMS_OUTPUT.PUT_LINE('SE REALIZEAZA O MODIFICARE PENTRU PROD '||:OLD.ID_PRODUS||', 
       se schimba pretul din '||:OLD.PRET_LISTA||' IN '||:NEW.PRET_LISTA); 
 -- NU FOLOSIM OPERATII LMD PE TABELA PE CARE AM DECLARAT TRIGGER FOR EACH ROW        
 SELECT NVL(SUM(PRET*CANTITATE),0) INTO V_VAL
 FROM RAND_COMENZI R
 --JOIN PRODUSE P ON R.ID_PRODUS=P.ID_PRODUS
 WHERE R.ID_PRODUS=:NEW.ID_PRODUS; 
 IF V_VAL > 5000 THEN
 DBMS_OUTPUT.PUT_LINE('VAL COMENZI: '||V_VAL);
 :NEW.PRET_LISTA:=:OLD.PRET_LISTA; -- DOAR PE TRIGGERI BEFORE
 END IF;      
END;
/


UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*1.05 WHERE CATEGORIE='hardware2';
UPDATE PRODUSE SET PRET_MIN=PRET_MIN*1.05 WHERE CATEGORIE='hardware2';


SELECT * FROM RAND_COMENZI ORDER BY ID_PRODUS;
SELECT * FROM PRODUSE ORDER BY ID_PRODUS;
UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*0.95 WHERE ID_PRODUS>=1770;