-- EXCEPTIE (RUN TIME ERROR)
 -- PREDEFINITE
 -- NON PREDEFINITE
 -- DEFINITE DE UTILIZATOR


set SERVEROUTPUT on
DECLARE
  NN_EXC EXCEPTION;
  PRAGMA EXCEPTION_INIT(NN_EXC,-2290);
begin
 insert into angajati(id_angajat,prenume) values (2002, 'John');
 EXCEPTION WHEN NN_EXC THEN
    dbms_output.put_line('Exceptie');
    dbms_output.put_line(sqlerrm);
end;
/

SA SE CITEASCA DE LA TASTATURA ID-UL UNEI COMENZI
DACA COMANDA EXISTA DAR NU ARE RANDURI SA SE RIDICE
O EXCEPTIE
SA SE TRATEZE ACEA EXCEPTIE
SELECT * FROM COMENZI ORDER BY 1 DESC;
SELECT * FROM RAND_COMENZI WHERE ID_COMANDA=2458;
DECLARE
  V_ID_COMANDA NUMBER:=2459;
  N1 NUMBER;
  N2 NUMBER;
BEGIN
  SELECT COUNT(*) INTO N1 FROM  COMENZI WHERE ID_COMANDA=V_ID_COMANDA;
  SELECT COUNT(*) INTO N2 FROM  RAND_COMENZI WHERE ID_COMANDA=V_ID_COMANDA;
  IF N1=1 AND N2=0 THEN    
    RAISE NO_DATA_FOUND; -- SE POT DECLANSA MANUAL EXC PREDEFINITE
  ELSE
    DBMS_OUTPUT.PUT_LINE('ALTA SITUATIE');
    DBMS_OUTPUT.PUT_LINE(N1||' '||N2);
  END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('EXISTA COMANDA DAR NU ARE RANDURI');    
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;
/

DECLARE
  V_ID_COMANDA NUMBER:=2459;
  N1 NUMBER;
  N2 NUMBER;
  NU_ARE_RANDURI EXCEPTION; -- EXCEPTIE DEF DE UTILIZATOR
BEGIN
  SELECT COUNT(*) INTO N1 FROM  COMENZI WHERE ID_COMANDA=V_ID_COMANDA;
  SELECT COUNT(*) INTO N2 FROM  RAND_COMENZI WHERE ID_COMANDA=V_ID_COMANDA;
  IF N1=1 AND N2=0 THEN    
    RAISE NU_ARE_RANDURI; 
  ELSE
    DBMS_OUTPUT.PUT_LINE('ALTA SITUATIE');
    DBMS_OUTPUT.PUT_LINE(N1||' '||N2);
  END IF;
  EXCEPTION
    WHEN NU_ARE_RANDURI THEN
    DBMS_OUTPUT.PUT_LINE('EXISTA COMANDA DAR NU ARE RANDURI');    
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;
/

DECLARE
  V_ID_COMANDA NUMBER:=2459;
  N1 NUMBER;
  N2 NUMBER;
  NU_ARE_RANDURI EXCEPTION; -- EXCEPTIE DEF DE UTILIZATOR
  PRAGMA EXCEPTION_INIT(NU_ARE_RANDURI,-20000);
BEGIN
  SELECT COUNT(*) INTO N1 FROM  COMENZI WHERE ID_COMANDA=V_ID_COMANDA;
  SELECT COUNT(*) INTO N2 FROM  RAND_COMENZI WHERE ID_COMANDA=V_ID_COMANDA;
  IF N1=1 AND N2=0 THEN    
    RAISE_APPLICATION_ERROR(-20000,'NU ARE RANDURI'); 
  ELSE
    DBMS_OUTPUT.PUT_LINE('ALTA SITUATIE');
    DBMS_OUTPUT.PUT_LINE(N1||' '||N2);
  END IF;
  EXCEPTION
    WHEN NU_ARE_RANDURI THEN
    DBMS_OUTPUT.PUT_LINE('EXISTA COMANDA DAR NU ARE RANDURI');    
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;
/

--Inside a PL/SQL block

DECLARE
  N NUMBER;
  FUNCTION GET_N_2 RETURN NUMBER IS
  BEGIN
    RETURN N*N;
  END;
BEGIN
    N:=91;
    DBMS_OUTPUT.PUT_LINE(GET_N_2);
END;
/

SELECT * FROM PRODUSE ORDER BY ID_PRODUS;

SA SE CONSTRUIASCA O PROCEDURA CARE PRIMESTE ID-UL UNUI PRODUS
SI UN PROCENT SI MARESTE CU RESPECTIVUL PROCENT PRETUL DE LISTA
A PRODUSULUI
SA SE AFISEZE PRETUL NOU

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD(P_ID_PRODUS NUMBER, 
  P_PROC NUMBER DEFAULT 10)  
IS
V_PRET_NOU NUMBER;
BEGIN
  UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROC)/100
    WHERE ID_PRODUS=P_ID_PRODUS;
  IF SQL%FOUND THEN  
  SELECT PRET_LISTA INTO V_PRET_NOU FROM PRODUSE
    WHERE ID_PRODUS=P_ID_PRODUS;
  DBMS_OUTPUT.PUT_LINE('S-A MARIT PRETUL CU '||P_PROC||'%');
  DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE '||V_PRET_NOU);
  END IF;
END;
/

EXEC MARESTE_PRET_PROD(1726,30);
EXEC MARESTE_PRET_PROD(P_ID_PRODUS=>1726,P_PROC=>15);

CALL MARESTE_PRET_PROD(1726,30);
-- BLOC APELATOR
BEGIN
MARESTE_PRET_PROD(P_ID_PRODUS=>1726,P_PROC=>15);
END;
/

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER, 
  P_PROC NUMBER DEFAULT 10, P_PRET_NOU OUT NUMBER)  
IS
BEGIN
  UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROC)/100
    WHERE ID_PRODUS=P_ID_PRODUS RETURNING PRET_LISTA
    INTO P_PRET_NOU;
  IF SQL%FOUND THEN    
  DBMS_OUTPUT.PUT_LINE('S-A MARIT PRETUL CU '||P_PROC||'%');
  DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE '||P_PRET_NOU);
  ELSE 
    RAISE_APPLICATION_ERROR(-20001,'NU EXISTA PRODUSUL '||P_ID_PRODUS);
  END IF;
END;
/

DECLARE
  V_PRET NUMBER;
  NU_EXISTA EXCEPTION;
  PRAGMA EXCEPTION_INIT(NU_EXISTA,-20001);
BEGIN
MARESTE_PRET_PROD3(P_ID_PRODUS=>8726,P_PROC=>15,P_PRET_NOU=>V_PRET);
DBMS_OUTPUT.PUT_LINE('___PRETUL NOU ESTE '||V_PRET);
EXCEPTION WHEN NU_EXISTA THEN
  DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA '||SQLERRM);
END;
/