EVALUARE
  - SEMINAR - 50% NOTA FINALA
      - TEST - 50% NOTA DE LA SEMINAR
      - PROIECT - 30% NOTA DE LA SEMINAR
      - ACTIVITATE - 20% NOTA DE LA SEMINAR
   NOTA MINIMA: 4.5/10
   - EXAMEN - 50% NOTA FINALA
       - GRILE
       - 2 SUBIECTE PRACTICE PL/SQL
   NOTA MINIMA: 4.5/10    
   
SQL
  - TABELE
       - COLOANE
       - RESTRICTII
       - RANDURI
  - VIEW  
  - SECVENTE
  - SINONIME
  - INDECSI
      - UNIQUE
      - NON UNIQUE
      
--SELECT * FROM ANGAJATI WHERE ID_ANGAJAT=150 OR ID_ANGAJAT!=151;      
--SELECT * FROM ANGAJATI WHERE ID_FUNCTIE='AD_VP';


PL/SQL
  - PROCEDURI
  - FUNCTII
  - PACHETE
  - DECLANSATORI
  
DECLARE
  -- OPTIONALA
BEGIN
  -- OBLIGATORIE
  EXCEPTION
     -- OPTIONALA
END;
/
SET SERVEROUTPUT ON
DECLARE
  N NUMBER(2) DEFAULT 10;
BEGIN
  N:=N+100;
  N:=N/0;
  DBMS_OUTPUT.PUT_LINE('N='||N);
  EXCEPTION
       WHEN ZERO_DIVIDE THEN
        DBMS_OUTPUT.PUT_LINE('IMPARTIREA LA ZERO NU ESTE PERMISA');
       WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE');
       DBMS_OUTPUT.PUT_LINE('SIGUR A APARUT O EXCEPTIE');

END;
/


  
  
  
  